version: '3'
services:
  app:
    build:
      context: .
    ports:
      - "8081:8080"
    volumes:
      - .:/var/www
    depends_on:
      - kafka
    networks:
      - mynetwork
  kafka:
    image: confluentinc/cp-kafka:6.0.0
    ports:
      - "9094:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2182"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - mynetwork
  zookeeper:
    image: confluentinc/cp-zookeeper:6.0.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2182
    networks:
      - mynetwork
networks:
  mynetwork: